name: Terraform Workflow

# Trigger the workflow on push to the main branch
on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=AKS-LAB" -backend-config="storage_account_name=esseldatalakedemo" -backend-config="container_name=tfstate" -backend-config="key=testtf"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        working-directory: ./env/dev/Base

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        working-directory: ./env/dev/Base

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        working-directory: ./env/dev/Base
